# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM nvidia/cudagl:11.2.2-base-ubuntu20.04

ENV NVIDIA_DRIVER_CAPABILITIES compute,graphics,utility

RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Berlin apt-get install -y --no-install-recommends \
    ca-certificates \
    libx11-xcb-dev \
    libxkbcommon-dev \
    libwayland-dev \
    libxrandr-dev \
    libegl1-mesa-dev \
    openjdk-17-jdk-headless \
    sudo \
    git \
    wget \
    sed \
    curl \
    libgl1-mesa-glx \
    libvulkan1 \
    libvulkan-dev \
    vulkan-utils \
    ocl-icd-opencl-dev \
    unzip \
    xz-utils \
    clinfo && \
    rm -rf /var/lib/apt/lists/*

RUN sudo mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
RUN sudo apt-get update
RUN apt-get install -qq --force-yes nodejs -y

# Install argos
RUN npm install -g @argos-ci/cli

# Link OpenCL ICD for Nvidia driver
RUN mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd
    
# Download current Vulkan SDK
ARG VULKAN_VERSION
RUN wget -q https://sdk.lunarg.com/sdk/download/${VULKAN_VERSION}/linux/vulkansdk-linux-x86_64-${VULKAN_VERSION}.tar.xz
RUN mkdir -p /opt/vulkan
RUN tar xf vulkansdk-linux-x86_64-${VULKAN_VERSION}.tar.xz -C /opt/vulkan
RUN chmod +x /opt/vulkan/${VULKAN_VERSION}/setup-env.sh
RUN /opt/vulkan/${VULKAN_VERSION}/setup-env.sh
RUN rm vulkansdk-linux-x86_64-*.tar.xz

# Copy Nvidia ICD
COPY nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json

# Download scenery example model files
RUN wget -q https://ulrik.is/scenery-demo-models_2022-07-28.zip && \
    unzip -q  scenery-demo-models_2022-07-28.zip && \
    rm scenery-demo-models_2022-07-28.zip

# Source Vulkan SDK config
ENV VULKAN_SDK_VERSION=${VULKAN_VERSION}
