# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM nvidia/cudagl:11.2.2-base-ubuntu20.04

ENV NVIDIA_DRIVER_CAPABILITIES compute,graphics,utility

RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Berlin apt-get install -y --no-install-recommends \
    libx11-xcb-dev \
    libxkbcommon-dev \
    libwayland-dev \
    libxrandr-dev \
    libegl1-mesa-dev \
    openjdk-11-jdk-headless \
    openjdk-8-jdk-headless \
    sudo \
    git \
    wget \
    sed \
    curl \
    libgl1-mesa-glx \
    libvulkan1 \
    libvulkan-dev \
    vulkan-utils \
    ocl-icd-opencl-dev \
    unzip \
    clinfo && \
    rm -rf /var/lib/apt/lists/*

# Install current Node version, and Argos CLI client
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -qq --force-yes nodejs && \
    npm install --save argos-cli && \
    mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

# Download current Vulkan SDK
ARG VULKAN_VERSION
RUN wget -q https://sdk.lunarg.com/sdk/download/${VULKAN_VERSION}/linux/vulkansdk-linux-x86_64-${VULKAN_VERSION}.tar.gz && \
    mkdir -p /opt/vulkan && \
    tar xfz vulkansdk-linux-x86_64-${VULKAN_VERSION}.tar.gz -C /opt/vulkan && \
    chmod +x /opt/vulkan/${VULKAN_VERSION}/setup-env.sh && \
    /opt/vulkan/${VULKAN_VERSION}/setup-env.sh && \
    rm vulkansdk-linux-x86_64-*.tar.gz

# Copy Nvidia ICD
COPY nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json

# Download scenery example model files
RUN wget -q https://ulrik.is/scenery-demo-models_2022-07-28.zip && \
    unzip -q  scenery-demo-models_2022-07-28.zip && \
    rm scenery-demo-models_2022-07-28.zip
